pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
  displayName: Install Python

- script: |
    curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    source $HOME/.poetry/env
    poetry --version
  displayName: 'Set up environment'

- script: |
    source $HOME/.poetry/env
    poetry --version
    poetry install
  displayName: 'Install dependencies'

- script: |
    source $HOME/.poetry/env
    make lint
  displayName: 'Lint'

- script: |
    source $HOME/.poetry/env
    make unit_test
  displayName: 'Unit test'

- script: |
    source $HOME/.poetry/env
    export PYPI_USERNAME=io_exception
    export PYPI_PASSWORD=$(PYPI_PASSWORD)
    make publish
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Publish package'
